Lection3 hw
Frolovek/Python_TestAutomation pull request #3
Opened 2022-10-18 18:05 UTC by Frolovek

Lection3 hw is completed

2022-10-18 20:11 UTC, alpakhomov requested changes
Оставил комменты к первому и третьему заданиям. Первое можно не исправлять, а вот hw3 поправь плз

2022-10-18 20:11 UTC, alpakhomov commented on Lection3_HW/hw1.py
> +                    result_for_line = line[:-1] + ' ' + validator.__name__ + '\n'
- файл на запись стоит открывать в режиме `w`; сейчас если два раза подряд запустить тесты, то они упадут, ибо `a` не перезаписывает файл с резульатом
- `lines = first.readlines()` считает весь файл в память. Лучше прямо сразу итерироваться по файлу строка за строкой `for line in first`

2022-10-18 20:11 UTC, alpakhomov commented on Lection3_HW/hw3.py
> +def custom_range(seq: Sequence, stop_, start=0, step=1) -> list:
В описании задания в начале дана выдержка из доки питона. Смысл такого кастомного range в том чтобы он следовал интерфейсу обычного range в питоне. Т.е. параметры всегда идут в определенном порядке (старт, стоп, степ). Передать их по ключу должно быть нельзя (иначе можно будет изменить порядок). Если бы функция всегда принимала все аргументы, ее сигнатура могла бы быть 
```python
def custom_range(seq, start, stop, step, /)
```
 так агрументы могут быть только позиционными. Но нужно еще предусмотреть варианты, когда передается только стоп, или (старт, стоп) и все это без возможности передавать keyword аргументы. 
Можно в test_hw3 добавить такой тест, он должен пройти на функции с правильной сигнатурой:
```python
import inspect


def test_positional_only_2():
    for _, kw in inspect.signature(custom_range).parameters.items():
        assert kw.default == inspect.Parameter.empty
```

2022-10-21 10:42 UTC, Frolovek commented on Lection3_HW/hw3.py
> +def custom_range(seq: Sequence, stop_, start=0, step=1) -> list:
Проапдейтила

2022-10-21 10:57 UTC, alpakhomov approved these changes
Все хорошо, принято!

2022-10-21 11:08 UTC, merged