Lection4, homework1
Frolovek/Python_TestAutomation pull request #4
Opened 2022-10-23 13:43 UTC by Frolovek

2022-10-23 15:19 UTC, alpakhomov requested changes
Оставил комментарии, поправь плз

2022-10-23 15:19 UTC, alpakhomov commented on Lection4_HW/hw1.py
> +        return datetime.timedelta(hw_deadline) < datetime.timedelta(0)
Объект timedelta возвращает разницу во времени. Сравнивать две дельты не имеет смысла. Здесь скорее всего в конструкторе дз нужно запоминать время, когда была создана домашка
```py
from datetime import datetime, timedelta

creation_date = datetime.now()
```
а затем сравнивать, что дата создания + дельта не больше текущего времени
```py
creation_date + timedelta(days=deadline) < datetime.now()
```
Второе - метод check_deadline скорее всего не должен иметь аннотаций staticmethod или classmethod. В этом методе мы работаем с полями экземпляра класса (дата создания, дедлайн). Значит такой метод должен обращаться к этим полям через self
```py
def check_deadline(self, ...):
    return self.creation_time + timedelta(self.deadline)...
```

2022-10-23 15:19 UTC, alpakhomov commented on Lection4_HW/hw1.py
> +class Student(Homework):
При наследовании у класса-родителя должны быть какие-то общие свойства со всеми его потомками. Т.е. например класс Animal может иметь потомков Cat, Dog, etc.
Студента и дз ничего не объединяет. Думаю что здесь наследования просто не должно быть. Аналогичная история с учителем.

2022-10-23 15:19 UTC, alpakhomov commented on Lection4_HW/hw1.py
> +            return hw
В этих трех строчках есть логическая проблема. 
Представь что у нас есть два студента. Учитель создает домашку, студент1 ее выполняет - теперь в объект дз записано его имя (автор) и решение.
После этого студент2 делает эту же домашку. Мы "затрем" решение студента1 - объект дз ведь один и тот же.
Решение этого - для выполненной дз должен быть отдельный объект (класс, например HomeworkResult). В этом методе будет проверка дедлайна, а если он еще не вышел - создание нового объекта с решением и автором.

2022-10-23 15:19 UTC, alpakhomov commented on Lection4_HW/hw1.py
> +    @classmethod
В этом методе ты не используешь ни self, ни cls. Значит он должен быть @staticmethod

2022-10-23 15:19 UTC, alpakhomov commented on Lection4_HW/hw1.py
> +            return False
В этом методе нужно первым делом проверить - есть ли уже такая домашка в homework_done? Если есть - просто вернуть True, видимо ее уже проверили до нас.
Структура словаря будет например такая `{Homework1: [HomeworkResult1, HomeworkResult2, ...], Homework2: ...}`
Значит когда мы добавляем новое решение - нужно добавить его в существующий список, не перезатирая то что там уже есть `list.append...`
Ну и строчка с None здесь наверное не нужна - если решение неправильное, то просто возвращаем False

2022-10-23 15:19 UTC, alpakhomov commented on Lection4_HW/hw1.py
> +    def reset_results(cls, *args):
Просто используй дефолтное значение вместо *args:
```py
def reset_results(cls, hw=None):
    if hw:
        ...
    else:
       ....
```

2022-10-24 17:18 UTC, Frolovek commented on Lection4_HW/hw1.py
> +        return datetime.timedelta(hw_deadline) < datetime.timedelta(0)
Добавила creation_date и поменяла check_deadline метод

2022-10-24 17:18 UTC, Frolovek commented on Lection4_HW/hw1.py
> +class Student(Homework):
Убрала лишнее

2022-10-24 17:18 UTC, Frolovek commented on Lection4_HW/hw1.py
> +            return hw
Добавила доп. класс, чтобы вписывать тула резалт

2022-10-24 17:18 UTC, Frolovek commented on Lection4_HW/hw1.py
> +    @classmethod
Убрала лишнее

2022-10-24 17:19 UTC, Frolovek commented on Lection4_HW/hw1.py
> +            return False
Добавила условий

2022-10-24 17:19 UTC, Frolovek commented on Lection4_HW/hw1.py
> +    def reset_results(cls, *args):
Проапдейтила

2022-10-24 18:22 UTC, alpakhomov approved these changes
Все хорошо, принято.

Пара мелких моментов:
- в `check_deadline` стоит убрать параметры метода, которые ты не используешь (creation_date и hw_deadline беруться из полей класса, передавать их не нужно)
- в Homework и ResultHomework не нужно переопределять метод `__hash__` - по умолчанию объекты будут равны только сами себе, это как-раз то что тебе нужно.

2022-10-25 07:55 UTC, merged